---
collections:
  tooltips:
    output: false
company_name: "INTEL CORPORATION"
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      comments: true
      layout: page
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: tooltips
    values:
      comments: true
      layout: page
      search: true
      tooltip: true
  -
    scope:
      path: ""
      type: posts
    values:
      comments: true
      layout: post
      search: true
      sidebar: home_sidebar
description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
disqus_shortname: ~
exclude:
  - .idea/
  - .gitignore
feedback_disable: true
feedback_email: tomjohnson1492@gmail.com
feedback_subject_line: "Jekyll documentation theme"
github_editme_path: clearcontainers/clearcontainers.github.io/edit/master/
google_analytics: ~
highlighter: rouge
host: "127.0.0.1"
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
  - jekyll-redirect-from
port: 4000
repository: clearcontainers/clearcontainers.github.io
sidebars:
  - home_sidebar
  - architecture_sidebar
  - mydoc_sidebar
  - product1_sidebar
  - product2_sidebar
  - other
site_title: "Intel® Clear Containers Documentation"
topnav_title: "Intel<sup>®</sup> Clear Containers"
url: "http://clearcontainers.github.io"
whitelist:
  - jekyll-redirect-from
